//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v12.1.1+6cdd561
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>location</summary>
	[PublishedModel("locations")]
	public partial class Locations : PublishedContentModel, IAmenitiesComponent, IArtwork, IBanner, IFnb, IProgramComponent, ISeo, ITransportComponent
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		public new const string ModelTypeAlias = "locations";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Locations, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Locations(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infodescription")]
		public virtual string Infodescription => this.Value<string>(_publishedValueFallback, "infodescription");

		///<summary>
		/// image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infoimage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops Infoimage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "infoimage");

		///<summary>
		/// isActive
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[ImplementPropertyType("infoisActive")]
		public virtual bool InfoisActive => this.Value<bool>(_publishedValueFallback, "infoisActive");

		///<summary>
		/// markdown
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infomarkdown")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString Infomarkdown => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "infomarkdown");

		///<summary>
		/// title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infotitle")]
		public virtual string Infotitle => this.Value<string>(_publishedValueFallback, "infotitle");

		///<summary>
		/// isActive
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[ImplementPropertyType("locationisActive")]
		public virtual bool LocationisActive => this.Value<bool>(_publishedValueFallback, "locationisActive");

		///<summary>
		/// title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("locationtitle")]
		public virtual string Locationtitle => this.Value<string>(_publishedValueFallback, "locationtitle");

		///<summary>
		/// variant
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("locationvariant")]
		public virtual string Locationvariant => this.Value<string>(_publishedValueFallback, "locationvariant");

		///<summary>
		/// description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("otherlocdescription")]
		public virtual string Otherlocdescription => this.Value<string>(_publishedValueFallback, "otherlocdescription");

		///<summary>
		/// isActive
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[ImplementPropertyType("otherlocisActive")]
		public virtual bool OtherlocisActive => this.Value<bool>(_publishedValueFallback, "otherlocisActive");

		///<summary>
		/// title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("otherloctitle")]
		public virtual string Otherloctitle => this.Value<string>(_publishedValueFallback, "otherloctitle");

		///<summary>
		/// slug
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("slug")]
		public virtual string Slug => this.Value<string>(_publishedValueFallback, "slug");

		///<summary>
		/// description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("amenitiesdescription")]
		public virtual string Amenitiesdescription => global::Umbraco.Cms.Web.Common.PublishedModels.AmenitiesComponent.GetAmenitiesdescription(this, _publishedValueFallback);

		///<summary>
		/// isActive
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("amenitiesisActive")]
		public virtual string AmenitiesisActive => global::Umbraco.Cms.Web.Common.PublishedModels.AmenitiesComponent.GetAmenitiesisActive(this, _publishedValueFallback);

		///<summary>
		/// list
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("amenitieslist")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> Amenitieslist => global::Umbraco.Cms.Web.Common.PublishedModels.AmenitiesComponent.GetAmenitieslist(this, _publishedValueFallback);

		///<summary>
		/// title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("amenitiestitle")]
		public virtual string Amenitiestitle => global::Umbraco.Cms.Web.Common.PublishedModels.AmenitiesComponent.GetAmenitiestitle(this, _publishedValueFallback);

		///<summary>
		/// description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("artworkdescription")]
		public virtual string Artworkdescription => global::Umbraco.Cms.Web.Common.PublishedModels.Artwork.GetArtworkdescription(this, _publishedValueFallback);

		///<summary>
		/// IsActive
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[ImplementPropertyType("artworkIsActive")]
		public virtual bool ArtworkIsActive => global::Umbraco.Cms.Web.Common.PublishedModels.Artwork.GetArtworkIsActive(this, _publishedValueFallback);

		///<summary>
		/// title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("artworktitle")]
		public virtual string Artworktitle => global::Umbraco.Cms.Web.Common.PublishedModels.Artwork.GetArtworktitle(this, _publishedValueFallback);

		///<summary>
		/// list
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("list")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> List => global::Umbraco.Cms.Web.Common.PublishedModels.Artwork.GetList(this, _publishedValueFallback);

		///<summary>
		/// isActive
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[ImplementPropertyType("asd")]
		public virtual bool Asd => global::Umbraco.Cms.Web.Common.PublishedModels.Banner.GetAsd(this, _publishedValueFallback);

		///<summary>
		/// title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bannertitle")]
		public virtual string Bannertitle => global::Umbraco.Cms.Web.Common.PublishedModels.Banner.GetBannertitle(this, _publishedValueFallback);

		///<summary>
		/// images
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("images")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockGridModel Images => global::Umbraco.Cms.Web.Common.PublishedModels.Banner.GetImages(this, _publishedValueFallback);

		///<summary>
		/// description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fnbdescription")]
		public virtual string Fnbdescription => global::Umbraco.Cms.Web.Common.PublishedModels.Fnb.GetFnbdescription(this, _publishedValueFallback);

		///<summary>
		/// isActive
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[ImplementPropertyType("fnbisActive")]
		public virtual bool FnbisActive => global::Umbraco.Cms.Web.Common.PublishedModels.Fnb.GetFnbisActive(this, _publishedValueFallback);

		///<summary>
		/// title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fnbtitle")]
		public virtual string Fnbtitle => global::Umbraco.Cms.Web.Common.PublishedModels.Fnb.GetFnbtitle(this, _publishedValueFallback);

		///<summary>
		/// outlets
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("outlets")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel Outlets => global::Umbraco.Cms.Web.Common.PublishedModels.Fnb.GetOutlets(this, _publishedValueFallback);

		///<summary>
		/// description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("programdescription")]
		public virtual string Programdescription => global::Umbraco.Cms.Web.Common.PublishedModels.ProgramComponent.GetProgramdescription(this, _publishedValueFallback);

		///<summary>
		/// isActive
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[ImplementPropertyType("programisActive")]
		public virtual bool ProgramisActive => global::Umbraco.Cms.Web.Common.PublishedModels.ProgramComponent.GetProgramisActive(this, _publishedValueFallback);

		///<summary>
		/// list
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("programlist")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> Programlist => global::Umbraco.Cms.Web.Common.PublishedModels.ProgramComponent.GetProgramlist(this, _publishedValueFallback);

		///<summary>
		/// title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("programtitle")]
		public virtual string Programtitle => global::Umbraco.Cms.Web.Common.PublishedModels.ProgramComponent.GetProgramtitle(this, _publishedValueFallback);

		///<summary>
		/// description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seodescription")]
		public virtual string Seodescription => global::Umbraco.Cms.Web.Common.PublishedModels.Seo.GetSeodescription(this, _publishedValueFallback);

		///<summary>
		/// image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seoimage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops Seoimage => global::Umbraco.Cms.Web.Common.PublishedModels.Seo.GetSeoimage(this, _publishedValueFallback);

		///<summary>
		/// keywords
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seokeywords")]
		public virtual string Seokeywords => global::Umbraco.Cms.Web.Common.PublishedModels.Seo.GetSeokeywords(this, _publishedValueFallback);

		///<summary>
		/// title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seotitle")]
		public virtual string Seotitle => global::Umbraco.Cms.Web.Common.PublishedModels.Seo.GetSeotitle(this, _publishedValueFallback);

		///<summary>
		/// routes
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("routes")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel Routes => global::Umbraco.Cms.Web.Common.PublishedModels.TransportComponent.GetRoutes(this, _publishedValueFallback);

		///<summary>
		/// description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("transportdesc")]
		public virtual string Transportdesc => global::Umbraco.Cms.Web.Common.PublishedModels.TransportComponent.GetTransportdesc(this, _publishedValueFallback);

		///<summary>
		/// isActive
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("transportisActive")]
		public virtual string TransportisActive => global::Umbraco.Cms.Web.Common.PublishedModels.TransportComponent.GetTransportisActive(this, _publishedValueFallback);

		///<summary>
		/// title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("transporttitle")]
		public virtual string Transporttitle => global::Umbraco.Cms.Web.Common.PublishedModels.TransportComponent.GetTransporttitle(this, _publishedValueFallback);
	}
}
